name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: autoreconf -i && sh configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: Save Test Results!
      if: always ()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: result
        path: tests/test-suite.log
    - name: make distcheck
      run: make distcheck
